lab6/urls.py
from django.urls import re_path, path, include
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.contrib.auth.views import LogoutView
    
urlpatterns = [
        path('lab-6/', index, name='index'),
        path('', index, name='index'),
        url(r'^add_todo/$', add_todo, name='add_todo'),
        path('profile/', profile, name='profile'),
        path('library/', library, name='library'),
        path('import_json/', import_json, name='import_json'),
        path('registration/', registration, name = 'registration'),
        path('register/', register, name='register'),
        path('email-check/', check_email, name = 'check_email'),
        path('subscriber/', subscriber, name='subscriber'),
        path('display-subscriber/', display_subscriber, name = 'display_subscriber'),
        path('', include('social_django.urls', namespace='social')),
        path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),
        path('update_count/', update_count, name="update_count"),
        ]

labppw/urls.py
from django.contrib import admin
from django.urls import path
import lab6.urls as lab6
from django.conf.urls import url
from django.urls import include, path, re_path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-6/', include('lab6.urls')),
    path('', include('lab6.urls')),
]

lab6/models.py
from django.db import models


class Todo(models.Model):
    title = models.CharField(max_length=27)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
 
class User(models.Model):
    nama = models.CharField(max_length = 100)
    email = models.EmailField(unique=True, db_index=True)
    password = models.CharField(max_length = 16)
# Create your models here.

lab6/forms.py
from django import forms
from .models import *

class Todo_Form(forms.Form):
    attrs = {
        'class' : 'form-control'
        }

    title = forms.CharField(label='Title', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    description = forms.CharField(label='Description', required=True, widget=forms.Textarea(attrs=attrs))

    class Meta:
        model = Todo

class Registration_Form(forms.Form):
    attrs = {
        'class' : 'form-control'
        }
    nama = forms.CharField(label = 'Nama', required = True, widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(label = 'E-mail', required = True, widget=forms.EmailInput(attrs=attrs))
    password = forms.CharField(label = 'Kata Sandi', required = False, max_length = 32, widget = forms.PasswordInput(attrs=attrs))

    class Meta:
        model = User

lab6/views.py
import requests
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from .forms import Todo_Form, Registration_Form
from .models import Todo, User
from django.views.decorators.csrf import csrf_exempt

todo = []
response = {}
def index(request):
    html = 'lab6.html'
    if (request.user.is_authenticated):
        todo = Todo.objects.all()
        response['todo'] = todo
        response['todo_form'] = Todo_Form
    return render(request, html, response)

def registration(request):
    html = 'registration.html'
    response['registration_form'] = Registration_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(title=response['title'],description=response['description'])
        todo.save()
        return HttpResponseRedirect('/lab-6/')
    else:
        return HttpResponseRedirect('/lab-6/')

def profile(request):
    return render(request, 'profile.html', {})

def library(request):
    return render(request, 'library.html')

def import_json(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=quilting"
    req = requests.get(url)
    resp = req.json()

    return JsonResponse(resp)

def display_subscriber(request):
    subscribers = User.objects.all().values('nama', 'email')
    subscribers_list = list(subscribers)
    return JsonResponse(subscribers_list, safe = False)
    

@csrf_exempt
def check_email(request):
    email_input = request.POST['email']
    list_email = User.objects.all()
    pesan = "Email tersebut telah terdaftar, mohon gunakan email lain"
    for email_to_check in list_email:
        if email_to_check.email == email_input:
            return JsonResponse({'message' : pesan})
    return JsonResponse({'message': 'Email belum terdaftar, silahkan lanjutkan'})

@csrf_exempt
def register(request):
    nama = request.POST['nama']
    email = request.POST['email']
    password = request.POST['password']
    User(nama=nama, email=email, password=password).save()
    return JsonResponse({'message': 'Data anda berhasil disimpan'})

def subscriber(request):
    return render(request, 'subscriber.html')

@csrf_exempt
def update_count(request):
    nambah = request.POST['nambah']
    if nambah:
        count = request.session.get('count', 0)
        request.session['count'] = count + 1
    else:
        count = request.session.get('count', 0)
        request.session['count'] = count - 1
    return JsonResponse({'count': request.session['count']})
# Create your views here.

lab6/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <title>Anditama's bio</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<style>
    body {
    background-image: linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%);
    }   
    .header_lib{
        margin-top: 100px;
    }
    .colorbefore{
        background-color: #fafafa;
    }
    .colorafter{
        background-color: cornflowerblue
    }
    #input-list{
        margin-top: 50px;
    }
    #hello{
        margin-top: 100px;
    }
    #profile_title{
        margin-top: 100px;
    }
    .footer {
	bottom: 0;
	width: 100%;
	line-height: 60px;
    color: #000000;
   }
    //updated ver

    .heading-primary {
      font-size: 2em;
      padding: 2em;
      text-align: center;
    }
    .accordion dl,
    .accordion-list {
      border: 1px solid #ddd;
      &:after {
        content: "";
        display: block;
        height: 1em;
        width: 100%;
        background-color: darken(#38cc70, 10%);
      }
    }
    .accordion dd,
    .accordion__panel {
      background-color: #eee;
      font-size: 1em;
      line-height: 1.5em;
    }
    .accordion p {
      padding: 1em 2em 1em 2em;
    }

    .accordion {
      position: relative;
      background-color: #eee;
    }
    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 2em 0 2em 0;
    }
    .accordionTitle,
    .accordion__Heading {
      text-align: center;
      font-weight: 700;
      padding: 2em;
      display: block;
      text-decoration: none;
      color: #000;
      transition: background-color 0.5s ease-in-out;
      border-bottom: 1px solid darken(#38cc70, 5%);
      &:before {
        content: "+";
        font-size: 1.5em;
        line-height: 0.5em;
        float: left;
        transition: transform 0.3s ease-in-out;
      }
      &:hover {
        background-color: darken(#38cc70, 10%);
      }
    }
    .accordionTitleActive,
    .accordionTitle.is-expanded {
      background-color: darken(#38cc70, 10%);
      &:before {
        transform: rotate(-225deg);
      }
    }
    .accordionItem {
      height: auto;
      overflow: hidden;
      //SHAME: magic number to allow the accordion to animate

      max-height: 50em;
      transition: max-height 1s;

      @media screen and (min-width: 48em) {
        max-height: 15em;
        transition: max-height 0.5s;
      }
    }

    .accordionItem.is-collapsed {
      max-height: 0;
    }
    .no-js .accordionItem.is-collapsed {
      max-height: auto;
    }
    .animateIn {
      animation: accordionIn 0.45s normal ease-in-out both 1;
    }
    .animateOut {
      animation: accordionOut 0.45s alternate ease-in-out both 1;
    }
    @keyframes accordionIn {
      0% {
        opacity: 0;
        transform: scale(0.9) rotateX(-60deg);
        transform-origin: 50% 0;
      }
      100% {
        opacity: 1;
        transform: scale(1);
      }
    }

    @keyframes accordionOut {
      0% {
        opacity: 1;
        transform: scale(1);
      }
      100% {
        opacity: 0;
        transform: scale(0.9) rotateX(-60deg);
      }
    }
    </style>
    
<body>
    <div class="wrap">
    <header>
    <nav class="navbar tocheck colorbefore fixed-top navbar-expand-md navbar-light">
    <a class="navbar-brand" href="{%url 'index' %}">Lab 6 PPW</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <!-- left navigation links -->
      <ul class="navbar-nav mr-auto">

        <!-- active navigation link -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>


        <!-- regular navigation link -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'library' %}">Library</a>
        </li>  
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration' %}">Subscribe</a>
        </li>  
          
        <li class="nav-item">
          <a class="nav-link" href="{% url 'subscriber' %}">Subscriber</a>
        </li>  
        </ul>
        
        <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <button type = "button" class= "changebutton btn btn-danger navbar-btn">Ganti warna</button>
        </li>
      </ul>
        
        </div>
        </nav>
        </header>
    </div>
    
<div class="container">
                <div class="jumbotron">
                <h1 class="display-4">Hello, apa kabar?</h1>
                {% if user.is_authenticated %}
                  <p class="lead">Welcome! <span>{{user.username}} to Anditama's website</span></p>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                  <hr class="my-4">
                {% else %}
                  <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
                    Login
                  </a>
                {% endif %}
         </div>
</div>
          
{% block content %}
{% endblock %}
    
    </body>
  <footer class = "footer tocheck colorbefore">
	<div class = "container">
		<span class = "text">M. Rizky Anditama</span>
		<span class = "text">© 2018 Copyright</span>
	</div>
  </footer>
    

<script>
    $(document).ready(function(){
        $(".changebutton").click(function(){
            if ($(".tocheck").hasClass("colorbefore")){
                $(".tocheck").removeClass("colorbefore").addClass("colorafter");
            }
            else{
                $(".tocheck").removeClass("colorafter").addClass("colorbefore");
            }
        });
    });
</script>
<script>
//uses classList, setAttribute, and querySelectorAll
//if you want this to work in IE8/9 youll need to polyfill these
(function(){
	var d = document,
	accordionToggles = d.querySelectorAll('.js-accordionTrigger'),
	setAria,
	setAccordionAria,
	switchAccordion,
  touchSupported = ('ontouchstart' in window),
  pointerSupported = ('pointerdown' in window);
  
  skipClickDelay = function(e){
    e.preventDefault();
    e.target.click();
  }

		setAriaAttr = function(el, ariaType, newProperty){
		el.setAttribute(ariaType, newProperty);
	};
	setAccordionAria = function(el1, el2, expanded){
		switch(expanded) {
      case "true":
      	setAriaAttr(el1, 'aria-expanded', 'true');
      	setAriaAttr(el2, 'aria-hidden', 'false');
      	break;
      case "false":
      	setAriaAttr(el1, 'aria-expanded', 'false');
      	setAriaAttr(el2, 'aria-hidden', 'true');
      	break;
      default:
				break;
		}
	};
//function
switchAccordion = function(e) {
  console.log("triggered");
	e.preventDefault();
	var thisAnswer = e.target.parentNode.nextElementSibling;
	var thisQuestion = e.target;
	if(thisAnswer.classList.contains('is-collapsed')) {
		setAccordionAria(thisQuestion, thisAnswer, 'true');
	} else {
		setAccordionAria(thisQuestion, thisAnswer, 'false');
	}
  	thisQuestion.classList.toggle('is-collapsed');
  	thisQuestion.classList.toggle('is-expanded');
		thisAnswer.classList.toggle('is-collapsed');
		thisAnswer.classList.toggle('is-expanded');
 	
  	thisAnswer.classList.toggle('animateIn');
	};
	for (var i=0,len=accordionToggles.length; i<len; i++) {
		if(touchSupported) {
      accordionToggles[i].addEventListener('touchstart', skipClickDelay, false);
    }
    if(pointerSupported){
      accordionToggles[i].addEventListener('pointerdown', skipClickDelay, false);
    }
    accordionToggles[i].addEventListener('click', switchAccordion, false);
  }
})();
    </script>
    
</html>

lab6/templates/lab6.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add_todo' %}">
            {% csrf_token %}
            {{todo_form}}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
        <br>
        </form>
    </div>
</section>
    
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Status</h2>
        <div class="flex">
            {% if todo %}
                {% for data in todo %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{data.title}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <br>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>
    
      
</div> 
{% endblock %}

lab6/templates/library.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script type="text/javascript">

$(document).ready(function(){
      $.ajax({
        url : "/import_json/",
        dataType : "json",
        success : function (importjson) {
            var books = importjson;
            for (var i=0; i<books.items.length; i++){
                var gambar = "<td>" + "<img src=\"" + books.items[i].volumeInfo.imageLinks.thumbnail + "\" /> </td>";       var judul = "<td>" + books.items[i].volumeInfo.title + "</td>";
                var penulis = "<td>" + books.items[i].volumeInfo.authors[0] + "</td>";
                var penerbit = "<td>" + books.items[i].volumeInfo.publisher + "</td>";
                var deskripsi = "<td>" + books.items[i].volumeInfo.description + "</td>";
                var favorit = "<td>" + "<button id=" + "'btn" + i + "'" + " class = 'btn cekfavoritbutton'><span class = 'cekfavorit glyphicon glyphicon-star-empty'></span></button>" + "</td>";
                $("#gambar").append(gambar); 
                $("#judul").append(judul);
                $("#penulis").append(penulis);
                $("#penerbit").append(penerbit);
                $("#deskripsi").append(deskripsi);
                $("#favorit").append(favorit);
                $("#btn" + i).click(cekFavorit(i));
            }
        },
  });
});
</script>
<script type = "text/javascript">
var nambah = true;
function cekFavorit(i){
    return function(){
        if ($("#btn" + i).find("span").hasClass("glyphicon-star-empty")){
            $("#btn" + i).find("span").removeClass("glyphicon-star-empty");
            $("#btn" + i).find("span").addClass("glyphicon-star");
        }
        else{
            $("#btn" + i).find("span").removeClass("glyphicon-star");
            $("#btn" + i).find("span").addClass("glyphicon-star-empty");
            nambah = false;
        }
        $.ajax({
            url: "/update_count/",
            data: {nambah : nambah},
            method:'POST',
            success : function (data){
                $("#count_favourite").html(data.count);
            }
        })
    }
}
</script>

<script>
    $(document).ready(function(){
        $("form").submit(function(event){
            var newtable = "<tr id='gambar'><th>Gambar</th></tr><tr id = 'judul'><th>Judul</th></tr><tr id='penulis'><th>Penulis</th></tr><tr id ='penerbit'><th>Penerbit</th></tr><tr id = 'deskripsi'><th>Deskripsi</th?</tr><tr id = 'favorit'><th>Favorit</th></tr>"
            $("tbody").html(newtable);
            var tosearch = $(".form-control").val();
            $.ajax({
                url : "https://www.googleapis.com/books/v1/volumes?q=" + tosearch,
                success : function(json){
                    var books = json;
                    for (var i=0; i<books.items.length; i++){
                    var gambar = "<td>" + "<img src=\"" + books.items[i].volumeInfo.imageLinks.thumbnail + "\" /> </td>";       var judul = "<td>" + books.items[i].volumeInfo.title + "</td>";
                    var penulis = "<td>" + books.items[i].volumeInfo.authors[0] + "</td>";
                    var penerbit = "<td>" + books.items[i].volumeInfo.publisher + "</td>";
                    var deskripsi = "<td>" + books.items[i].volumeInfo.description + "</td>";
                    var favorit = "<td>" + "<button id=" + "'btn" + i + "'" + " class = 'btn cekfavoritbutton'><span class = 'cekfavorit glyphicon glyphicon-star-empty'></span></button>" + "</td>";
                    $("#gambar").append(gambar); 
                    $("#judul").append(judul);
                    $("#penulis").append(penulis);
                    $("#penerbit").append(penerbit);
                    $("#deskripsi").append(deskripsi);
                    $("#favorit").append(favorit);
                    $("#btn" + i).click(cekFavorit(i));
                    }
                }
            });
            event.preventDefault();
        });
    });
</script>

<div class="container">
    <br/>
	<div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm">
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>
                                    <!--end of col-->
                                    <div class="col">
                                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="Search topics or keywords">
                                    </div>
                                    <!--end of col-->
                                    <div class="col-auto">
                                        <button class="btn btn-lg btn-success" type="submit">Search</button>
                                    </div>
                                    <!--end of col-->
                                </div>
                            </form>
                        </div>
                        <!--end of col-->
                    </div>
</div>

<div class="container-fluid">
    <div class = "header_lib">
        <center>
            <h3>Total favorit: <span id = "count_favourite">{{request.session.count}}</span></h3></center>
    </div>
    
    <div id = "table_lib "class = "table table-responsive">
    <table>
        <tbody>
            <tr id='gambar'>
                <th>Gambar</th>
            </tr>
            <tr id = "judul">
                <th>Judul</th>
            </tr>
            <tr id="penulis">
                <th>Penulis</th>
            </tr>
            <tr id ="penerbit">
                <th>Penerbit</th>
            </tr>
            <tr id = "deskripsi">
                <th>Deskripsi</th>
            </tr>
            <tr id = "favorit">
                <th>Favorit</th>
            </tr>
        </tbody>
        </table>
    </div>
</div>
{% endblock %}

lab6/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "container">
<div id= "profile_title">
<center>
    <h1>Profile</h1></center>
</div>

<div id= "profile_photo">
    <center><img src = https://s33.postimg.cc/3nwvr364v/foto.jpg>
    </center>
</div>
<div id = "name">
    <center><h3>Muhammad Rizky Anditama</h3></center></div>
<div class="container">
          <h1 class="heading-primary">Deskripsi diri</h1>
          <div class="accordion">
            <dl>
              <dt>
                <a href="#accordion1" aria-expanded="false" aria-controls="accordion1" class="tocheck colorbefore accordion-title accordionTitle js-accordionTrigger">Aktivitas</a>
              </dt>
              <dd class="accordion-content accordionItem is-collapsed" id="accordion1" aria-hidden="true">
                <ul>
                    <li>University Student of Fasilkom UI</li>
                    <li>Indonesian Nationality</li>
                    <li>Avid Gamer</li>
                    <li>Undertaking web programming and web developing course</li>
                  </ul>
              </dd>
              <dt>
                <a href="#accordion2" aria-expanded="false" aria-controls="accordion2" class="tocheck colorbefore accordion-title accordionTitle js-accordionTrigger">
                  Pengalaman</a>
              </dt>
              <dd class="accordion-content accordionItem is-collapsed" id="accordion2" aria-hidden="true">
                <ul>
                    <li>Staff of Wisuda Genap</li>
                    <li>Staff of Compfest</li>
                    <li>Staff of Open House Fasilkom</li>
                    <li>Staff of Pemira Fasilkom</li>
                  </ul>
              </dd>
              <dt>
                <a href="#accordion3" aria-expanded="false" aria-controls="accordion3" class="tocheck colorbefore accordion-title accordionTitle js-accordionTrigger">
                  Prestasi
                </a>
              </dt>
              <dd class="accordion-content accordionItem is-collapsed" id="accordion3" aria-hidden="true">
                <ul>
                    <li>Participation in National Chemistry Competition at High School</li>
                  </ul>
              </dd>
            </dl>
          </div>
        </div>
</div>
{% endblock %}

lab6/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id="hello">
    <center><h1>Subscribe me</h1></center>
</div>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST">
            {% csrf_token %}
            {{registration_form}}
        <br>
        </form>
        <div class='text-center'><button class='btn btn-success' disabled id='id_button'>Submit</button></div>
    </div>
</section>

<script type="text/javascript">
    $('<p id="info_email" class="text-right"><b></b></p>').insertAfter('#id_email');
    $('<p></p>').insertAfter('#id_nama');

    $('#id_email').change(function() {
                $.ajax({
                    method: "POST",
                    url : '/email-check/',
                    data: { email: $('#id_email').val()},
                    success: function(msg) {
                        $('#info_email b').html(msg.message);
                }
            });
        });
    
    function allValid(){
        var valid = true;
        $('body input').each(function() {
            if($(this).val() == ''){
                 valid = false;
            }
        });
        if( $('#info_email b').html() != 'Email belum terdaftar, silahkan lanjutkan'){
            valid = false;
            console.log("tes")
        }
        return valid;
    }
    
    $('#id_nama, #id_email, #id_password').bind('keyup', function() {
        if (allValid()){
            $("#id_button").removeAttr('disabled');
        }else{
            $("#id_button").attr('disabled', 'true');
        }
    });
    
    $('#id_button').click(function() {
            $.ajax({
                method: 'POST',
                url: '/register/',
                data: { nama: $("#id_nama").val(),
                        email: $("#id_email").val(),
                        password: $("#id_password").val()
                },
                success: function(msg) {
                    $("#id_nama").val('');
                    $("#id_email").val('');
                    $("#id_password").val('');
                    $('#info_email b').html('');
                    alert(msg.message);
                }
            })
        });


</script>


{% endblock %}

lab6/templates/subscriber.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script type = text/javascript>
$(document).ready(function(){
      $.ajax({
        url : "/display-subscriber/",
        dataType : "json",
        success : function (importsubs) {
            for (var i=0; i<importsubs.length; i++){
                var nama = "<td>" + importsubs[i].nama + "</td>";
                var email = "<td>" + importsubs[i].email+  "</td>";
                var button = "<td>" + "<button id=" + "'btn" + i + "'" + " class = 'btn cekfavoritbutton'><span class = 'cekfavorit glyphicon 	glyphicon glyphicon-remove'></span></button>" + "</td>";
                $("#nama").append(nama); 
                $("#email").append(email);
                $("#unsubscribe").append(button);
            }
        },
  });
});
    
</script>


<div class="container-fluid">
    <div class = "header_lib">
        <center>
            <h3>Subscriber list</h3></center>
    </div>
    
    <div id = "table_lib "class = "table table-responsive">
    <table>
        <tbody>
            <tr id='nama'>
                <th>Nama</th>
            </tr>
            <tr id = "email">
                <th>E-mail</th>
            </tr>
            <tr id = "unsubscribe">
                <th>Unsubscribe</th>
            </tr>
        </tbody>
        </table>
    </div>
</div>

{% endblock %}

lab6/templates/welcome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}